package/docker/odoo/Dockerfile
In this PR, we have removed the unused paths that are being copied to our Docker image. These modules where previously added to facilitate the use of a single endpoint. After much discussion, we have agreed to move away from this single endpoint approach, thus making these modules obsolete.
=> [Rahul] | Fix. Remove Unused Paths

bahmni_api_feed/models/api_event_worker.py
Jira --> [BAH-3411](https://bahmni.atlassian.net/browse/BAH-3411), [BAH-3329](https://bahmni.atlassian.net/browse/BAH-3329),[BAH-3369](https://bahmni.atlassian.net/browse/BAH-3362)
In this PR below issues are resolved.
- Customer Address update issue was fixed.
- Email key error has been covered in this commit.
- Default customer creation has been handled in this PR.
=> BAH-3411 | Fixed. Address issues and email issue

bahmni_account/__manifest__.py, bahmni_api_feed/models/api_event_worker.py, bahmni_api_feed/models/order_save_service.py, bahmni_sale/models/sale_order_line.py
Jira --> [BAH-3440](https://bahmni.atlassian.net/browse/BAH-3440)
In this PR following changes all done.
1. While creating the order with miss matched UOM in the odoo the qty create as a 0 qty.
2. In odoo inbuilt module sale have the field product_uom_qty default value as 1, while using the inheritance changed the default value as 0.
3. While creating the order throw the API the sale order default value changes a 0 instead of 1.
=> BAH-3440 | Fixed. order line qty logic changed.

package/docker/odoo/odoo.conf
This PR adds dbFIlter configuration to odoo.conf which will allow implementations to create multiple databases within a single instance of Odoo.
=> BAH-3564 | Add dbFilter to show all the databases created with Odoo

bahmni_api_feed/models/order_save_service.py
This PR updates the description field of Sale order line in quotation to show the actual quantity and unit of measure passed in the API payload.
Medications in Bahmni:
Quotation in Odoo 16:
=> BAH-3562 | Fix. Show the actual quantity and unit passed in payload in the description of sale order line

bahmni_purchase/__manifest__.py
This PR adds bahmni_sale as a dependency of bahmni_purchase, since the purchase module adds a menu item to the Bahmni Masters menu
=> Fix. Module dependency error and container failing to start

bahmni_sale/models/__init__.py, bahmni_sale/models/sale_order.py, bahmni_sale/models/stock_move_line.py
Jira --> [BAH-3638](https://bahmni.atlassian.net/browse/BAH-3638)
While checking the sale order confirm auto delivery logic was implemented with the boolean config field, we can able to control the automation logic with the config setting, with available in the odoo settings.
Once the sale order confirm automatically delivery will get confirmed, as per the logic stock will reused in the mapped lot in the sale order line.
**Following controls all added in the Sale order.**
1. If the mapped lot not having available Qty means system will indicate that the  qty engouht qty not avaiable with the available qty details.
2. If the same product mapped twice with the same lot number means system will  indicate that the same product same lot mapped twice, user …
=> BAH-3638 | Add. Automate delivery process based on sale order confirmation.

bahmni_api_feed/models/drug_data_service.py
This PR adds a context filter to find all products based on UUID irrespective of whether it is active or not.
=> BAH-3663 | Add. Disable active product filtering during drug creation

bahmni_stock/views/stock_pick_lot_view.xml
This PR hides the `From` and `To` fields in the internal transfer page detailed operations section, as the location will be selected above
=> Refactor. Hide From and To location fields in internal transfer page

package/docker/odoo/Dockerfile, package/docker/odoo/odoo.conf
This PR refactors the way community modules are bundled into the docker image.
- All the modules downloaded from Odoo Community is grouped under community_modules directory.
- The docker image bundles it inside the `/opt/bahmni-erp/bahmni-addons/community_modules` directory.
- The addition path is added to `odoo.conf`
=> Refactor. Bundling of community modules in docker image

community_modules/br_custom_list_view/static/src/xml/record_highlight.xml
This PR fixes the alignment issues happening in Invoices page when custom module for row numbers is installed. https://apps.odoo.com/apps/modules/16.0/br_custom_list_view/
JIRA --> https://bahmni.atlassian.net/browse/BAH-3776
Before:
After:
=> BAH-3776 | Fix. Serial number alignment issue in Accounting/Invoices Views

bahmni_account/models/account_invoice.py, bahmni_account/views/account_invoice_view.xml
This PR adds a new computed field named as `invoice_total` which is aware of discount and round off amount fields.
=> BAH-3778 | Add, Field for showing invoice total after calculating discount and round off

bahmni_sale/models/sale_order.py, bahmni_sale/security/security_groups.xml
This PR adds in the feature to redirect the user to Payments screen on confirming the sale order. This happens only when auto invoice validation is enabled and redirection is enabled under user technical rights.
=> BAH-3828 | Add. Redirect to payments on sale order confirmation based on user toggle

bahmni_product/views/product_supplierinfo_view.xml, bahmni_purchase/__manifest__.py, bahmni_purchase/models/__init__.py, bahmni_purchase/models/price_markup_table.py, bahmni_purchase/models/purchase_order.py, bahmni_purchase/models/purchase_order_line.py, bahmni_purchase/models/res_config_settings.py, bahmni_purchase/views/res_config_inherit.xml, bahmni_stock/models/stock_move_line.py, bahmni_stock/models/stock_picking.py, bahmni_stock/views/stock_pick_lot_view.xml
This PR adds in changes to the PO confirmation flow.
- Fixes loading of MRP field while creating a purchase quotation. This bug is addressed as the product supplier info was not updated with mrp filed on confirming the previous order. https://bahmni.atlassian.net/browse/BAH-3751
- The Product price details are updated based on the PO details when the config is toggled on and on confirming the Purchase quotation. https://bahmni.atlassian.net/browse/BAH-3736. The MRP field is also shown in the Product under Purchase tab
- The lots are updated with the price details on validating the stock picking for the related purchase order
Refactorings:
- Formatting fixes on few files
- Extracted a function for calculating markup price in `price.markup.table` model to keep it consistent and reusable
- …
=> BAH-3736, BAH-3751 | Product and Lot price details updation on PO Confirmation and Stock Picking

bahmni_api_feed/models/order_save_service.py, bahmni_sale/models/res_config_settings.py, bahmni_sale/views/res_config_settings_view.xml
Now with sale price markup toggle enabled aswell we are getting multiple order lines for the quotation.
=> BAH-3779|Deepthi M|Fixed the issue with creating order lines when sale price mark up rule is enabled

bahmni_api_feed/models/order_save_service.py
This PR fixes the exception thrown when multiple products are in the same order with batch splitting. Also fixed setting of sale_price when different batches are selected
=> BAH-3779 | Fix. Error when multiple products have batch selection

bahmni_purchase/views/purchase_views.xml, bahmni_sale/views/sale_order_views.xml
In xml views for sale_order/purchase_order, the domain filter was getting added to a duplicate **partner_id** field - because there was the attribute **after**  instead of **attributes** to add the required domain filter. 
Changed it to attribute **attributes** to add the attribute on the existing partner_id field (and also changed the syntax accordingly)
=> BAH-3702 | Fix. Customer/Vendor added from Sale-Order/Purchase-Order forms are not getting customer_rank/supplier_rank

bahmni_stock/models/stock_move_line.py, bahmni_stock/models/stock_production_lot.py
This PR adds `digits` attribute to custom price specific fields for lot based price information.
This is to keep in sync with product price precision as defined in default Odoo. https://github.com/odoo/odoo/blob/16.0/addons/product/models/product_product.py#L26
=> BAH-4006 | Fix. Digit precision for lot specific price details

bahmni_sale/views/sale_order_views.xml
This PR disables the creation of lots from Sales Quotation page. 
Creation of lots and quantity modifications should only done from Purchase flows or Inventory flows.
JIRA: https://bahmni.atlassian.net/browse/BAH-3963
=> BAH-3963 | Fix. Disable creation of lots from Sales page

bahmni_sale/models/sale_order.py, bahmni_sale/views/sale_order_views.xml
This PR adds a check to run the product quantity availability validations only for lines with product and excludes line types note and section.
JIRA: https://bahmni.atlassian.net/browse/BAH-3964
=> BAH-3964 | Fix. Check for quantity availability only for product_lines in Sale Quotation lines

package/docker/odoo/Dockerfile
This PR updates the Dockerfile to add the `odoo10_data_import` module to get it packaged with the bahmni/odoo-16 docker image.
=> BAH-3569 | Fix. Bundle Odoo 10 Data import module to Docker image

bahmni_reports/report/stock_report.py
This PR fixes the stock statement report to add the line items even when the product contains only inventory adjustments
=> BAH-3833 | Fix. Add line items to stock report when there is only inventory adjustment

package/docker/odoo/Dockerfile
This PR fixes the file ownership set for `odoo.conf` file. This is crucial in persisting the database master password of Odoo. Without this ownership Odoo fails to write the updated password with an error `ERROR: couldn't write the config file` 
JIRA: https://bahmni.atlassian.net/browse/BAH-4054
=> BAH-4054 | Fix. File permissions for Odoo conf file

package/docker/odoo/Dockerfile
This PR adds the `bahmni_customer_return` module as an optional module for implementers to install on a need basis to the Docker image.
=> BAH-4132 | Add. Customer return module to docker image as an optional module

bahmni_sale/models/sale_order.py
This PR fixes the issue with the calculation of Invoice Amount due when confirming a sale order. This happens because the discount and round off are applied twice since the recalculation of amount_total field is disabled in base Odoo by this [commit](https://github.com/odoo/odoo/commit/cc3a060e67a2f1015ea02b589dcf6a7e7eff1e90).
=> BAH-4151 | Fix. Invoice amount double calculation due to Odoo base upgrade
