Bahmni/bahmni-odoo-modules

.github/workflows/build_publish_odoo.yml

JIRA -> [BAH-3241](https://bahmni.atlassian.net/browse/BAH-3241)
In this PR, a workflow that builds and publishes the `Odoo:16` image to docker hub has been added.

BAH-3241 | Add. Workflow To Build and Push Odoo 16

---

package/docker/odoo/Dockerfile

The dockerfile has been updated such that the newly created modules are now being added to our odoo service as an addon modules.

BAH-3234 | Add. New Addon Modules

---

package/docker/odoo/Dockerfile

In this PR, the following changes are made:
Module Installation Command: We've updated the command in the Dockerfile to streamline the installation process for both the base modules and custom modules that we've incorporated. This installation now occurs when the container starts, thanks to the CMD instruction.

[Rahul] | Add. Custom Modules To Dockerfile

---

.github/workflows/trigger_odoo16_env_deploy.yml

This PR adds a workflow to trigger workflow in bahmni-docker repository to trigger deployments on the odoo 16 environment

BAH-3385 | Trigger deployments to odoo 16 environment

---

restful_api/controllers/main.py
restful_api/models/api_data_feed.py

This PR updates the auth method of every api endpoint to `user` so that session and privilege will be handled by Odoo authentication logic.
Custom token validation logic has been removed

BAH-3374 | Fix. Warehouse error due to insufficient privlieges

---

package/docker/odoo/Dockerfile

This reverts commit 0430107248870630348a3893b3542b035a07e52d.
This fixes the container failed to start issue. JIRA --> https://bahmni.atlassian.net/browse/BAH-3427

Revert "[Rahul] | dockerfile-changes | Add. base As a Custom Module"

---

bahmni_api_feed/models/drug_data_service.py

Jira --> [BAH-3441](https://bahmni.atlassian.net/browse/BAH-3441)
In this PR, Following changes have been made
- Product category added under the parent category tree in the bahmni_api_feed.

BAH-3441 | Fix. product category added under the parent tree.

---

bahmni_api_feed/models/order_save_service.py

Jira --> [BAH-3442](https://bahmni.atlassian.net/browse/BAH-3442)
In this PR, Following changes have been made.
- Odoo UserError changed as a log warning, without the available product all the available product create as a order product,not available product has been skipped and the warning indicate in the log.

BAH-3442 | Refactor. UserError changed as a log warning

---

bahmni_account/__manifest__.py
bahmni_sale/__manifest__.py

Jira --> [BAH-3444](https://bahmni.atlassian.net/browse/BAH-3444)
In this PR AttributeError was fixed while adding the dependence modules in the responsible modules.

BAH-3444 | Fix. AttributeError was fixed

---

jss_data_import/models/models.py

This PR adds changes to migrate the `Internal Reference` Field of product definition from OpenERP 7 to Odoo 16

BAH-3572 | Sync default code attribute when migrating products from OpenERP 7

---

bahmni_sale/models/sale_order.py

JIRA: https://bahmni.atlassian.net/browse/BAH-3578

BAH-3578 | Fix. Variable reference which causes failure of multiple quotation creation

---

bahmni_api_feed/models/api_event_worker.py
bahmni_api_feed/models/order_save_service.py

This PR refactors the finding of Shop for quotation sync based on rules as defined in the card. https://bahmni.atlassian.net/browse/BAH-3565

BAH-3565 | Fix. Finding of shop mapping based on rules

---

bahmni_address_mapping/models/address_mapping_service.py
bahmni_api_feed/models/api_event_worker.py

This PR updates the address mapping service to reset the address fields which are passed as null.
JIRA: https://bahmni.atlassian.net/browse/BAH-3521

BAH-3521 | Fix. Reset address fields when the api payload sends fields as null

---

bahmni_purchase/models/price_markup_table.py

Jira --> [BAH-3589](https://bahmni.atlassian.net/browse/BAH-3589)
1. Validation has been Added.

BAH-3589 | Refactor. Validation has been Added

---

bahmni_sale/__manifest__.py
bahmni_sale/views/custom_filters.xml

This PR adds the following custom filters to the Quotations and Invoices page.
- Today Sales
- Yesterday Sales
- Today Invoices
- Yesterday Invoices
The default is also set to the `Today Sales` in quotations page and `Today Invoices` in invoices page, removing the default `My Quotations` filter.

BAH-3627 | Add custom filters to Quotations and Invoices page

---

bahmni_sale/models/res_config_settings.py

Jira --> [BAH-3591](https://bahmni.atlassian.net/browse/BAH-3591)
1. Container is broken for res config file has been updated.

[Karthi] | BAH-3591 | Refactor. Res config issue has been fxed

---

bahmni_purchase/models/price_markup_table.py

Jira --> [BAH-3589](https://bahmni.atlassian.net/browse/BAH-3589)
1. Missing Validation has been Added.

BAH-3589 | Refactor. Missing Validation has been Added

---

bahmni_reports/__manifest__.py
bahmni_reports/report/__init__.py
bahmni_reports/report/sale_discount_head_statement.py
bahmni_reports/report/sale_discount_head_statement_view.xml

Jira --> [BAH-3652](https://bahmni.atlassian.net/browse/BAH-3652)
1. Sales Discount Statement Report has been added.

BAH-3652 | Add. Sales Discount Statement Report.

---

package/docker/odoo/Dockerfile

This PR adds the `bahmni_reports` module to the docker image

BAH-3549 | Add. Bahmni Reports module to docker build

---

bahmni_sale/models/sale_order.py
bahmni_sale/views/sale_order_views.xml

Jira --> [BAH-3611](https://bahmni.atlassian.net/browse/BAH-3611)
1. Discount issue has been fixed.

BAH-3611 | Refactor. Discount issue has been fixed

---

bahmni_sale/models/sale_order_line.py

Jira --> [BAH-3598](https://bahmni.atlassian.net/browse/BAH-3598)
1. Refactor. Markup cost price logic has been modify.

BAH-3598 | Refactor. Markup cost price logic has been modify

---

bahmni_reports/report/product_reorder_list.py
bahmni_reports/report/product_reorder_list_view.xml
bahmni_reports/report/reports_menu_view.xml

Jira --> [BAH-3549](https://bahmni.atlassian.net/browse/BAH-3549)
1. Refactor. Menu align has been updated.

[Karthi] | BAH-3549 | Refactor. Menu align has been updated

---

bahmni_stock/views/stock_production_lot_view.xml

Jira --> [BAH-3670](https://bahmni.atlassian.net/browse/BAH-3670)
1. This issue happens due to version mismatch.
2. Lot view added in product qty in tree view.

BAH-3670 | Add. Show lot quantity in Lots/Serial Numbers page

---

bahmni_stock/models/__init__.py
bahmni_stock/models/stock_move.py

Reverts Bahmni/bahmni-odoo-modules#113

Revert "BAH-3614 | Refactor. Delivery based Customer Item return p…"

---

bahmni_initializer/__init__.py
bahmni_initializer/__manifest__.py
bahmni_initializer/models/__init__.py
bahmni_initializer/models/address_seed.py
bahmni_initializer/security/ir.model.access.csv
package/docker/odoo/Dockerfile
package/resources/data/address.seed.csv

JIRA -> [BAH-3505](https://bahmni.atlassian.net/browse/BAH-3505)
This PR introduces a seed data initializer. The addon module is designed to extract data from the 'address.seed.csv' file and generate a record for each row in the village.village, district.subdistrict, state.district tables.

BAH-3505 | Add. Bahmni Address Seed Initializer

---

bahmni_stock/models/stock_move_line.py

Jira --> [BAH-3736](https://bahmni.atlassian.net/browse/BAH-3736)
1. Import Module issue has been fixed.

BAH-3736 | Refactor. Import module issue has been fixed.

---

bahmni_sale/models/sale_order_line.py

Live | Refactor. Lot choose by location issue fixed via api

---

bahmni_sale/views/sale_order_views.xml
bahmni_stock/models/stock_production_lot.py
community_modules/stock_picking_filter_lot/views/stock_move_line_view.xml

…Batch number listed location based has been restriction done.
1. Previous Outstanding Balance field read-only has been set in sale order.
2. Sale order and Internal transfer location wise restriction done.

Refactor. Sale Order and Internal Transfer Batch number show quantity available

---

bahmni_auto_payment_reconciliation/report/report_invoice_inherit.xml
bahmni_auto_payment_reconciliation/views/account_report.xml

This PR fixes the file names for receipt print and summary print for payments.

BAH-3749 | Fix. Receipt and summary print file names

---

bahmni_sale/models/sale_order.py

Changed the column to compute the value from **amount_residual** to **amount_residual_signed**

BAH-3790 | Fix. Previous Outstanding Field value in Sale Quotations

---

bahmni_reports/report/stock_report.py

Jira --> [BAH-3833](https://bahmni.atlassian.net/browse/BAH-3833)
1. Undefined inventory_adj_outward_qty variables has been removed.

BAH-3833 | Refactor. Undefined variables has been removed

---

bahmni_auto_payment_reconciliation/models/account_payment.py
bahmni_auto_payment_reconciliation/report/report_invoice_inherit.xml

This PR enhances the bahmni_auto_payment_reconciliation module to support for refund payments.
- The payment type will be selected as `Send` when the Current Outstanding is less than zero.
- When the payment is confirmed, the amount gets reconciled with the open credit invoices.
- Validations has been added to validate the type of payment based on outstanding.
JIRA: https://bahmni.atlassian.net/browse/BAH-4155

BAH-4155 | Refactor. Payment reconciliation to support for refund payments

---

bahmni_customer_return/models/bahmni_customer_return.py
bahmni_customer_return/views/bahmni_customer_return_views.xml

This PR adds roundoff calculation for total return amount

BAH-4141 | Add. Round off calculation for total return amount

---

bahmni_customer_return/models/bahmni_customer_return.py
bahmni_customer_return/views/bahmni_customer_return_views.xml

This PR adds a field `Billed Amount` which shows the total value of return after subtracting the discount and before applying round off.

BAH-4141 | Add. Field to show billed amount before round off in return form

---

bahmni_reports/report/stock_report.py

This PR fixes the issue with double calculation inventory adjustment quantity in opening stock of stock statement report.

BAH-4151 | FIx. Double caluculation of inventory adjustment quantity
